const EXPORTS = [
  { format: "csv", label: "CSV", title: "ดาวน์โหลดเป็นไฟล์ CSV (เปิดด้วย Excel ได้)" },
  { format: "json", label: "JSON", title: "ดาวน์โหลดเป็นไฟล์ JSON" },
];

// Exports are generated by /api/analytics/export so they include every stored
// project, not only what this page renders.
export default function AnalyticsExportButtons({ query = "" }) {
  return <div className="analytics-export"><span>ส่งออกข้อมูล</span>{EXPORTS.map(({ format, label, title }) => <a key={format} href={`/api/analytics/export?format=${format}${query ? `&${query}` : ""}`} download title={title}>{label}</a>)}</div>;
}
